version: '3.7'

services:
  web1:
    image: 'app1'
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    hostname: web1
    ports:
      - '3000:3000'

  projectb:
    image: 'app2'
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    hostname: projectb
    ports:
      - '4000:4000'
#   postgres:
#     image: postgres:latest
#     environment:
#       POSTGRES_DB: mydatabase
#       POSTGRES_USER: myuser
#       POSTGRES_PASSWORD: mypassword
#     volumes:
#       - nfs-share:/var/lib/postgresql/data


# volumes:
#   nfs-share:
#     driver: local
#     driver_opts:
#       type: nfs
#       o: addr=localhost,rw
#       device: ":/path/to/nfs/share"
